include: package:lints/recommended.yaml

analyzer:
  exclude:
    - "build/**"
  
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    # Custom rules can be added here
    avoid_print: true