name: share_my_apk
description: "Build and upload Flutter Android APKs to Diawi and Gofile.io faster than you can say 'It's compiling!' A fun and powerful CLI tool."
version: 0.3.0-alpha

# Package metadata for pub.dev
homepage: https://github.com/wm-jenildgohel/share_my_apk
repository: https://github.com/wm-jenildgohel/share_my_apk
issue_tracker: https://github.com/wm-jenildgohel/share_my_apk/issues
documentation: https://github.com/wm-jenildgohel/share_my_apk/blob/master/README.md


# Topics for better discoverability
topics:
  - apk-builder
  - android
  - upload
  - diawi
  - gofile
  - deployment

environment:
  sdk: ^3.8.1

dependencies:
  args: ^2.5.0
  http: ^1.2.2
  logging: ^1.2.0
  path: ^1.9.0
  process_run: ^1.0.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.2

executables:
  share_my_apk:add