name: share_my_apk
description: "A powerful command-line tool to build and upload your Flutter Android APKs directly to various services like Diawi and Gofile.io."
version: 0.3.0-alpha

# Package metadata for pub.dev
homepage: https://github.com/wm-jenildgohel/share_my_apk
repository: https://github.com/wm-jenildgohel/share_my_apk
issue_tracker: https://github.com/wm-jenildgohel/share_my_apk/issues


# Topics for better discoverability
topics:
  - apk-builder
  - android
  - upload
  - diawi
  - gofile
  - deployment

environment:
  sdk: ^3.8.1

dependencies:
  args: ^2.5.0
  http: ^1.2.2
  logging: ^1.2.0
  path: ^1.9.0
  process_run: ^1.0.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.2

executables:
  share_my_apk:
