name: share_my_apk
description: "Build and upload Flutter Android APKs to Diawi and Gofile.io faster than you can say 'It's compiling!' A fun and powerful CLI tool."
version: 0.3.1

# Package metadata for pub.dev
homepage: https://github.com/wm-jenildgohel/share_my_apk
repository: https://github.com/wm-jenildgohel/share_my_apk
issue_tracker: https://github.com/wm-jenildgohel/share_my_apk/issues
documentation: https://github.com/wm-jenildgohel/share_my_apk/blob/master/README.md


# Topics for better discoverability
topics:
  - apk-builder
  - android
  - upload
  - diawi
  - gofile
  - deployment

environment:
  sdk: ^3.8.1

dependencies:
  args: ^2.7.0
  http: ^1.4.0
  logging: ^1.3.0
  path: ^1.9.1
  process_run: ^1.2.4
  yaml: ^3.1.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.2

executables:
  share_my_apk: