name: share_my_apk
description: "A powerful command-line tool to build and upload your Flutter APKs directly to various services like Diawi and Gofile.io. This package can also be used as a library."
version: 0.1.0-alpha

# Package metadata for pub.dev
homepage: https://github.com/wm-jenildgohel/share_my_apk
repository: https://github.com/wm-jenildgohel/share_my_apk
issue_tracker: https://github.com/wm-jenildgohel/share_my_apk/issues
documentation: https://github.com/wm-jenildgohel/share_my_apk/tree/main/doc

# Topics for better discoverability
topics:
  - flutter
  - apk
  - build
  - upload
  - diawi
  - gofile
  - ci-cd
  - deployment
  - mobile
  - android

# Screenshots for pub.dev (uncomment when screenshots are available)
# screenshots:
#   - description: 'Command-line interface in action'
#     path: screenshots/cli_example.png
#   - description: 'APK organization structure'
#     path: screenshots/file_organization.png

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  args: ^2.5.0
  flutter:
    sdk: flutter
  http: ^1.2.2
  logging: ^1.2.0
  process_run: ^1.0.0
  yaml: ^3.1.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package

executables:
  share_my_apk:
