name: Update Contributors

on:
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday
  workflow_dispatch:  # Allow manual trigger
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/update-contributors.yml'

jobs:
  update-contributors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Contributors
        uses: akhilmhdh/contributors-readme-action@v2.3.6
        with:
          readme_path: 'README.md'
          columns_per_row: 7
          collaborators: 'direct'
          commit_message: 'docs: update contributors list [skip ci]'
          committer_username: 'github-actions[bot]'
          committer_email: 'github-actions[bot]@users.noreply.github.com'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}